window.data = [
  {
    'brand': 'BMW',
    'model': 'X5',
    'price': 64281,
    'color': 'Black',
    'country': 'Germany',
    'year': 2020,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'XC90',
    'price': 67125,
    'color': 'Red',
    'country': 'Sweden',
    'year': 2022,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Toyota',
    'model': 'Highlander',
    'price': 48136,
    'color': 'Red',
    'country': 'Japan',
    'year': 2021,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'McLaren',
    'model': '720S',
    'price': 310083,
    'color': 'Silver',
    'country': 'UK',
    'year': 2017,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Tesla',
    'model': 'Model Y',
    'price': 73521,
    'color': 'Blue',
    'country': 'USA',
    'year': 2020,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volkswagen',
    'model': 'Amarok',
    'price': 46295,
    'color': 'Silver',
    'country': 'Germany',
    'year': 2019,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'BMW',
    'model': 'iX',
    'price': 103801,
    'color': 'Grey',
    'country': 'Germany',
    'year': 2017,
    'fuelType': 'Petrol',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Dodge',
    'model': 'Challenger',
    'price': 40124,
    'color': 'White',
    'country': 'USA',
    'year': 2021,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'BMW',
    'model': 'X7',
    'price': 98938,
    'color': 'Grey',
    'country': 'Germany',
    'year': 2017,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Tesla',
    'model': 'Model S',
    'price': 101347,
    'color': 'Blue',
    'country': 'USA',
    'year': 2019,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Honda',
    'model': 'CR-V',
    'price': 35285,
    'color': 'Grey',
    'country': 'Japan',
    'year': 2020,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'S60',
    'price': 54966,
    'color': 'Black',
    'country': 'Sweden',
    'year': 2024,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Chevrolet',
    'model': 'Suburban',
    'price': 75109,
    'color': 'Green',
    'country': 'USA',
    'year': 2020,
    'fuelType': 'Hybrid',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Porsche',
    'model': 'Cayenne',
    'price': 86758,
    'color': 'White',
    'country': 'Germany',
    'year': 2021,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Volvo',
    'model': 'S90',
    'price': 70430,
    'color': 'Green',
    'country': 'Sweden',
    'year': 2018,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Volvo',
    'model': 'V90',
    'price': 60001,
    'color': 'Grey',
    'country': 'Sweden',
    'year': 2017,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Honda',
    'model': 'Civic',
    'price': 32786,
    'color': 'Black',
    'country': 'Japan',
    'year': 2023,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Bentley',
    'model': 'Bentayga',
    'price': 178636,
    'color': 'Grey',
    'country': 'UK',
    'year': 2017,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Ford',
    'model': 'Escape',
    'price': 29166,
    'color': 'Black',
    'country': 'USA',
    'year': 2021,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'BMW',
    'model': 'X3',
    'price': 53664,
    'color': 'White',
    'country': 'Germany',
    'year': 2024,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Mitsubishi',
    'model': 'Pajero',
    'price': 55621,
    'color': 'Silver',
    'country': 'Japan',
    'year': 2020,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Dodge',
    'model': 'Hornet',
    'price': 42322,
    'color': 'Green',
    'country': 'USA',
    'year': 2021,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Kia',
    'model': 'Sorento',
    'price': 38382,
    'color': 'Green',
    'country': 'South Korea',
    'year': 2018,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Toyota',
    'model': 'C-HR',
    'price': 34616,
    'color': 'Blue',
    'country': 'Japan',
    'year': 2017,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Porsche',
    'model': 'Panamera',
    'price': 122317,
    'color': 'Black',
    'country': 'Germany',
    'year': 2022,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Hyundai',
    'model': 'Ioniq 5',
    'price': 57955,
    'color': 'Silver',
    'country': 'South Korea',
    'year': 2017,
    'fuelType': 'Petrol',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'V60',
    'price': 62809,
    'color': 'Blue',
    'country': 'Sweden',
    'year': 2019,
    'fuelType': 'Hybrid',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Audi',
    'model': 'E-Tron',
    'price': 81377,
    'color': 'Green',
    'country': 'Germany',
    'year': 2019,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volkswagen',
    'model': 'Golf',
    'price': 39019,
    'color': 'Green',
    'country': 'Germany',
    'year': 2020,
    'fuelType': 'Petrol',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'McLaren',
    'model': 'Artura',
    'price': 235195,
    'color': 'Green',
    'country': 'UK',
    'year': 2024,
    'fuelType': 'Diesel',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Volvo',
    'model': 'V90',
    'price': 70784,
    'color': 'White',
    'country': 'Sweden',
    'year': 2017,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Tesla',
    'model': 'Model 3',
    'price': 59223,
    'color': 'Red',
    'country': 'USA',
    'year': 2022,
    'fuelType': 'Diesel',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Jeep',
    'model': 'Gladiator',
    'price': 44445,
    'color': 'Grey',
    'country': 'USA',
    'year': 2018,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'S60',
    'price': 57409,
    'color': 'Grey',
    'country': 'Sweden',
    'year': 2022,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Mazda',
    'model': 'CX-50',
    'price': 30197,
    'color': 'Black',
    'country': 'Japan',
    'year': 2024,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Bentley',
    'model': 'Bentayga',
    'price': 196024,
    'color': 'Blue',
    'country': 'UK',
    'year': 2023,
    'fuelType': 'Hybrid',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Ford',
    'model': 'Escape',
    'price': 27017,
    'color': 'Black',
    'country': 'USA',
    'year': 2020,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Toyota',
    'model': 'RAV4',
    'price': 39077,
    'color': 'Grey',
    'country': 'Japan',
    'year': 2020,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Hyundai',
    'model': 'Sonata',
    'price': 27119,
    'color': 'Green',
    'country': 'South Korea',
    'year': 2017,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Aston Martin',
    'model': 'Rapide',
    'price': 257505,
    'color': 'Black',
    'country': 'UK',
    'year': 2020,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Hyundai',
    'model': 'Ioniq 5',
    'price': 47000,
    'color': 'Green',
    'country': 'South Korea',
    'year': 2018,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'XC60',
    'price': 66002,
    'color': 'White',
    'country': 'Sweden',
    'year': 2021,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Tesla',
    'model': 'Model Y',
    'price': 69846,
    'color': 'White',
    'country': 'USA',
    'year': 2019,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'S60',
    'price': 52173,
    'color': 'White',
    'country': 'Sweden',
    'year': 2017,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Volvo',
    'model': 'XC90',
    'price': 74928,
    'color': 'Red',
    'country': 'Sweden',
    'year': 2018,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Porsche',
    'model': 'Panamera',
    'price': 92409,
    'color': 'Red',
    'country': 'Germany',
    'year': 2018,
    'fuelType': 'Hybrid',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Volvo',
    'model': 'XC40',
    'price': 47803,
    'color': 'Silver',
    'country': 'Sweden',
    'year': 2020,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Genesis',
    'model': 'G90',
    'price': 87993,
    'color': 'Black',
    'country': 'South Korea',
    'year': 2022,
    'fuelType': 'Petrol',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Jeep',
    'model': 'Gladiator',
    'price': 64028,
    'color': 'Silver',
    'country': 'USA',
    'year': 2017,
    'fuelType': 'Diesel',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Mitsubishi',
    'model': 'Lancer',
    'price': 31057,
    'color': 'Grey',
    'country': 'Japan',
    'year': 2017,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Dodge',
    'model': 'Challenger',
    'price': 50332,
    'color': 'Silver',
    'country': 'USA',
    'year': 2019,
    'fuelType': 'Hybrid',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Bentley',
    'model': 'Continental GT',
    'price': 253838,
    'color': 'Grey',
    'country': 'UK',
    'year': 2021,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Kia',
    'model': 'Seltos',
    'price': 24368,
    'color': 'Red',
    'country': 'South Korea',
    'year': 2020,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Audi',
    'model': 'Q7',
    'price': 67045,
    'color': 'Blue',
    'country': 'Germany',
    'year': 2024,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Mazda',
    'model': 'CX-50',
    'price': 35920,
    'color': 'Black',
    'country': 'Japan',
    'year': 2019,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Lexus',
    'model': 'RX',
    'price': 58223,
    'color': 'Red',
    'country': 'Japan',
    'year': 2018,
    'fuelType': 'Hybrid',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Mazda',
    'model': 'CX-30',
    'price': 31532,
    'color': 'Blue',
    'country': 'Japan',
    'year': 2023,
    'fuelType': 'Hybrid',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Genesis',
    'model': 'G80',
    'price': 56823,
    'color': 'Red',
    'country': 'South Korea',
    'year': 2022,
    'fuelType': 'Diesel',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Hyundai',
    'model': 'Kona',
    'price': 28527,
    'color': 'Blue',
    'country': 'South Korea',
    'year': 2021,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Nissan',
    'model': 'Altima',
    'price': 28356,
    'color': 'Grey',
    'country': 'Japan',
    'year': 2018,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Audi',
    'model': 'A6',
    'price': 62457,
    'color': 'Red',
    'country': 'Germany',
    'year': 2017,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Bentley',
    'model': 'Continental GT',
    'price': 233012,
    'color': 'Black',
    'country': 'UK',
    'year': 2020,
    'fuelType': 'Diesel',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Kia',
    'model': 'Sportage',
    'price': 30206,
    'color': 'Black',
    'country': 'South Korea',
    'year': 2017,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Kia',
    'model': 'Sportage',
    'price': 29712,
    'color': 'Black',
    'country': 'South Korea',
    'year': 2024,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Rolls-Royce',
    'model': 'Ghost',
    'price': 434004,
    'color': 'Green',
    'country': 'UK',
    'year': 2017,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Nissan',
    'model': 'Pathfinder',
    'price': 36209,
    'color': 'Blue',
    'country': 'Japan',
    'year': 2022,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Bentley',
    'model': 'Bentayga',
    'price': 203954,
    'color': 'Silver',
    'country': 'UK',
    'year': 2017,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Hyundai',
    'model': 'Tucson',
    'price': 33839,
    'color': 'Blue',
    'country': 'South Korea',
    'year': 2021,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Porsche',
    'model': 'Panamera',
    'price': 98018,
    'color': 'Silver',
    'country': 'Germany',
    'year': 2018,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Land Rover',
    'model': 'Discovery',
    'price': 72102,
    'color': 'Grey',
    'country': 'UK',
    'year': 2019,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'S90',
    'price': 62661,
    'color': 'White',
    'country': 'Sweden',
    'year': 2021,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Aston Martin',
    'model': 'Rapide',
    'price': 250306,
    'color': 'Grey',
    'country': 'UK',
    'year': 2020,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Jeep',
    'model': 'Renegade',
    'price': 31663,
    'color': 'White',
    'country': 'USA',
    'year': 2017,
    'fuelType': 'Hybrid',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Tesla',
    'model': 'Model Y',
    'price': 74537,
    'color': 'Red',
    'country': 'USA',
    'year': 2023,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Honda',
    'model': 'Ridgeline',
    'price': 43694,
    'color': 'Green',
    'country': 'Japan',
    'year': 2020,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'BMW',
    'model': '5 Series',
    'price': 60609,
    'color': 'Blue',
    'country': 'Germany',
    'year': 2023,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Bentley',
    'model': 'Continental GT',
    'price': 231134,
    'color': 'Black',
    'country': 'UK',
    'year': 2017,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Mitsubishi',
    'model': 'Pajero',
    'price': 52110,
    'color': 'Red',
    'country': 'Japan',
    'year': 2023,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Volvo',
    'model': 'XC90',
    'price': 62256,
    'color': 'Green',
    'country': 'Sweden',
    'year': 2022,
    'fuelType': 'Petrol',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Porsche',
    'model': '911',
    'price': 167758,
    'color': 'Black',
    'country': 'Germany',
    'year': 2022,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Porsche',
    'model': 'Taycan',
    'price': 109867,
    'color': 'Grey',
    'country': 'Germany',
    'year': 2021,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Genesis',
    'model': 'G80',
    'price': 54138,
    'color': 'Red',
    'country': 'South Korea',
    'year': 2021,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Toyota',
    'model': 'GR Supra',
    'price': 69989,
    'color': 'Green',
    'country': 'Japan',
    'year': 2024,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Volvo',
    'model': 'S90',
    'price': 72458,
    'color': 'Silver',
    'country': 'Sweden',
    'year': 2020,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'BMW',
    'model': 'X5',
    'price': 71134,
    'color': 'Green',
    'country': 'Germany',
    'year': 2023,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'BMW',
    'model': '5 Series',
    'price': 74496,
    'color': 'Red',
    'country': 'Germany',
    'year': 2019,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Dodge',
    'model': 'Charger',
    'price': 43667,
    'color': 'Red',
    'country': 'USA',
    'year': 2018,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'C40 Recharge',
    'price': 57940,
    'color': 'Black',
    'country': 'Sweden',
    'year': 2018,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Kia',
    'model': 'Sportage',
    'price': 26144,
    'color': 'Silver',
    'country': 'South Korea',
    'year': 2021,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Aston Martin',
    'model': 'Vantage',
    'price': 174254,
    'color': 'Black',
    'country': 'UK',
    'year': 2019,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Hyundai',
    'model': 'Sonata',
    'price': 32470,
    'color': 'Grey',
    'country': 'South Korea',
    'year': 2024,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'V90',
    'price': 78540,
    'color': 'Grey',
    'country': 'Sweden',
    'year': 2024,
    'fuelType': 'Diesel',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'XC60',
    'price': 52949,
    'color': 'Red',
    'country': 'Sweden',
    'year': 2022,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Volvo',
    'model': 'XC60',
    'price': 66423,
    'color': 'Silver',
    'country': 'Sweden',
    'year': 2020,
    'fuelType': 'Hybrid',
    'electric': true,
    'transmission': 'Manual'
  },
  {
    'brand': 'Toyota',
    'model': 'Land Cruiser 250',
    'price': 102577,
    'color': 'Blue',
    'country': 'Japan',
    'year': 2021,
    'fuelType': 'Petrol',
    'electric': false,
    'transmission': 'Manual'
  },
  {
    'brand': 'Genesis',
    'model': 'G90',
    'price': 83335,
    'color': 'Grey',
    'country': 'South Korea',
    'year': 2020,
    'fuelType': 'Electric',
    'electric': true,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Dodge',
    'model': 'Durango',
    'price': 50447,
    'color': 'Grey',
    'country': 'USA',
    'year': 2023,
    'fuelType': 'Hybrid',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Honda',
    'model': 'Insight',
    'price': 23378,
    'color': 'Blue',
    'country': 'Japan',
    'year': 2018,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Bentley',
    'model': 'Flying Spur',
    'price': 224872,
    'color': 'Black',
    'country': 'UK',
    'year': 2022,
    'fuelType': 'Diesel',
    'electric': false,
    'transmission': 'Automatic'
  },
  {
    'brand': 'Volvo',
    'model': 'S60',
    'price': 50824,
    'color': 'Grey',
    'country': 'Sweden',
    'year': 2021,
    'fuelType': 'Electric',
    'electric': false,
    'transmission': 'Manual'
  }
];
